name: Publish Package

on:
  push:
    branches:
      - master
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - run: dotnet build -c Release
      - run: dotnet pack -c Release

      - name: Setup NuGet
        run: dotnet nuget add source "https://nuget.pkg.github.com/OWNER/index.json" --name "github" --username OWNER --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Publish NuGet to Github Packages
        run: dotnet nuget push "bin/Release/*.nupkg" --source "github" --api-key ${{ env.GITHUB_TOKEN }}